---
# Manifest file downloaded from fusion
externalId: tr-create_asset_hierarchy
name: create_asset_hierarchy
query:
    file: transformation.sql
destination:
    type: asset_hierarchy
ignoreNullFields: true
shared: true
action: upsert
schedule:
    interval: 0 * * * *
    isPaused: false
dataSetExternalId: all
# Specify credentials separately like this:
